title:            Vincent Dumoulin
tagline:          Personal website of Vincent Dumoulin
description:      Personal website of Vincent Dumoulin
#Comment out url when working locally to resolve base urls correctly
url: http://vdumoulin.github.io

# Owner/author information
owner:
  name:           Vincent Dumoulin
  avatar:         avatar.png
  bio:            "WRITEME"
  email:          vincent.dumoulin@umontreal.ca
  twitter:        dumoulinv        
  github:         vdumoulin       
  disqus:         vdumoulin
  

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Publications
    url: /publications
  - title: Software
    url: /software
  - title: RSS
    url: /feed

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
pygments:    true
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
